export const phrases = [
  'Love grows quietly in the smallest moments.',
  'The earth speaks softly to those who listen.',
  'Every sunset is a reminder that endings can be beautiful.',
  'Kindness leaves footprints where words cannot.',
  'The stars shine brightest when the night is darkest.',
  'Peace begins with a gentle heart.',
  'Flowers bloom without asking for permission.',
  'A calm mind can hear the music of the wind.',
  'Love is the language every soul understands.',
  'The ocean teaches patience with every wave.',
  'Happiness often hides in ordinary days.',
  'The moon never rushes, yet it always arrives on time.',
  'Every tree is a poem written by nature.',
  'Hope is a light that survives every storm.',
  'The sky changes every day and never loses its beauty.',
  'A loving heart creates its own sunshine.',
  'Nature never competes, yet everything finds its place.',
  'Sometimes silence is the most honest conversation.',
  'The beauty of life lives in its imperfections.',
  'Every season carries a lesson worth learning.',
  'Love is not found, it is grown.',
  'The river never looks back, yet it reaches the sea.',
  'Gentle souls make the world softer.',
  'Even the smallest seed dreams of becoming a forest.',
  'Peace is the space between two deep breaths.',
  'The sun rises every morning without asking for applause.',
  'Every cloud is part of a larger sky.',
  'The heart remembers what truly matters.',
  'Nature heals what hurry cannot.',
  'Love turns ordinary places into homes.',
  'The mountains remind us how small worries can be.',
  'A single act of kindness can echo for years.',
  'The rain nourishes the earth without expecting gratitude.',
  'Joy often arrives unannounced.',
  'Every leaf carries the story of a season.',
  'The world becomes brighter when shared with others.',
  'Love is a bridge between souls.',
  'The forest grows strongest in quiet patience.',
  'Peace is not the absence of noise, but the presence of balance.',
  'The horizon exists to remind us there is always more to discover.',
  'A warm heart is more powerful than a loud voice.',
  'Nature creates masterpieces without a signature.',
  'The night sky is proof that darkness can be beautiful.',
  'Every moment of gratitude is a moment of abundance.',
  'Love asks for presence, not perfection.',
  'The wind carries stories across the world.',
  'Life unfolds like a garden, one season at a time.',
  'True peace cannot be rushed.',
  'The most beautiful things often grow slowly.',
  'Where love lives, beauty follows.',
];
