export const footerPhrases = {
  en: [
    'Love grows quietly in the smallest moments.',
    'The earth speaks softly to those who listen.',
    'Every sunset is a reminder that endings can be beautiful.',
    'Kindness leaves footprints where words cannot.',
    'The stars shine brightest when the night is darkest.',
    'Peace begins with a gentle heart.',
    'Flowers bloom without asking for permission.',
    'A calm mind can hear the music of the wind.',
    'Love is the language every soul understands.',
    'The ocean teaches patience with every wave.',
    'Happiness often hides in ordinary days.',
    'The moon never rushes, yet it always arrives on time.',
    'Every tree is a poem written by nature.',
    'Hope is a light that survives every storm.',
    'The sky changes every day and never loses its beauty.',
    'A loving heart creates its own sunshine.',
    'Nature never competes, yet everything finds its place.',
    'Sometimes silence is the most honest conversation.',
    'The beauty of life lives in its imperfections.',
    'Every season carries a lesson worth learning.',
    'Love is not found, it is grown.',
    'The river never looks back, yet it reaches the sea.',
    'Gentle souls make the world softer.',
    'Even the smallest seed dreams of becoming a forest.',
    'Peace is the space between two deep breaths.',
    'The sun rises every morning without asking for applause.',
    'Every cloud is part of a larger sky.',
    'The heart remembers what truly matters.',
    'Nature heals what hurry cannot.',
    'Love turns ordinary places into homes.',
    'The mountains remind us how small worries can be.',
    'A single act of kindness can echo for years.',
    'The rain nourishes the earth without expecting gratitude.',
    'Joy often arrives unannounced.',
    'Every leaf carries the story of a season.',
    'The world becomes brighter when shared with others.',
    'Love is a bridge between souls.',
    'The forest grows strongest in quiet patience.',
    'Peace is not the absence of noise, but the presence of balance.',
    'The horizon exists to remind us there is always more to discover.',
    'A warm heart is more powerful than a loud voice.',
    'Nature creates masterpieces without a signature.',
    'The night sky is proof that darkness can be beautiful.',
    'Every moment of gratitude is a moment of abundance.',
    'Love asks for presence, not perfection.',
    'The wind carries stories across the world.',
    'Life unfolds like a garden, one season at a time.',
    'True peace cannot be rushed.',
    'The most beautiful things often grow slowly.',
    'Where love lives, beauty follows.',
  ],
  ru: [
    'Любовь растёт тихо — в тех самых мгновениях, которые мы часто не замечаем.',
    'Природа говорит шёпотом, но её голос слышен каждому, кто умеет слушать.',
    'Каждый закат напоминает нам о том, что даже прощание может быть прекрасным.',
    'Доброта оставляет след там, где слова оказываются бессильны.',
    'Самые яркие звёзды видны именно в самые тёмные ночи.',
    'Настоящий мир начинается в сердце, которое умеет быть мягким.',
    'Цветы не спрашивают разрешения, чтобы расцвести.',
    'Тишина иногда говорит больше, чем тысячи сказанных слов.',
    'Любовь — это язык, который понимает каждая душа.',
    'Океан учит терпению каждой своей волной.',
    'Счастье чаще всего прячется в самых обычных днях.',
    'Луна никогда не спешит, но всегда приходит вовремя.',
    'Каждое дерево — это стихотворение, написанное самой природой.',
    'Надежда остаётся светом даже тогда, когда вокруг бушует буря.',
    'Небо меняется каждый день, но никогда не теряет своей красоты.',
    'Любящее сердце способно создавать собственное солнце.',
    'В природе нет соревнования, но каждый находит своё место.',
    'Иногда молчание становится самым честным разговором.',
    'Красота жизни живёт в её несовершенстве.',
    'Каждое время года приносит урок, который стоит усвоить.',
    'Любовь не находят — её выращивают день за днём.',
    'Река никогда не оглядывается назад, но всегда достигает моря.',
    'Добрые души делают этот мир немного теплее.',
    'Даже маленькое семя мечтает однажды стать лесом.',
    'Покой рождается между двумя глубокими вдохами.',
    'Солнце восходит каждое утро, не ожидая похвалы.',
    'Каждое облако — часть огромного неба.',
    'Сердце помнит то, что действительно важно.',
    'Природа исцеляет то, с чем не справляется спешка.',
    'Любовь превращает обычные места в дом.',
    'Горы напоминают нам, насколько малы бывают наши тревоги.',
    'Один добрый поступок способен звучать эхом долгие годы.',
    'Дождь питает землю, ничего не требуя взамен.',
    'Радость часто приходит тогда, когда её совсем не ждёшь.',
    'Каждый лист хранит историю своего времени.',
    'Мир становится светлее, когда мы делимся им друг с другом.',
    'Любовь — это мост между двумя душами.',
    'Лес становится сильнее благодаря терпению и времени.',
    'Гармония — это не отсутствие шума, а присутствие равновесия.',
    'Горизонт существует, чтобы напоминать: впереди всегда есть что открыть.',
    'Тёплое сердце сильнее самого громкого голоса.',
    'Природа создаёт шедевры без подписи автора.',
    'Ночное небо доказывает, что даже тьма может быть красивой.',
    'Каждый миг благодарности делает жизнь богаче.',
    'Любовь ждёт не совершенства, а искреннего присутствия.',
    'Ветер переносит истории через города, моря и континенты.',
    'Жизнь раскрывается как сад — постепенно, сезон за сезоном.',
    'Настоящий покой не любит спешки.',
    'Самые прекрасные вещи растут медленно.',
    'Там, где живёт любовь, всегда появляется красота.',
    'Иногда достаточно остановиться на мгновение, чтобы заметить, как прекрасен мир вокруг нас.',
    'Каждый рассвет приносит новую возможность начать сначала и стать немного лучше, чем вчера.',
    'Самые ценные вещи в жизни нельзя увидеть глазами — их можно только почувствовать сердцем.',
    'Время проходит, но воспоминания о доброте остаются с нами гораздо дольше любых слов.',
    'Когда человек находит внутренний покой, весь мир вокруг начинает звучать иначе.',
    'Настоящая красота не стремится привлечь внимание — она просто существует.',
    'Даже самый долгий путь начинается с одного шага, сделанного с верой в себя.',
    'Мы не можем остановить ветер, но можем научиться наполнять им свои паруса.',
    'Иногда самые важные встречи происходят тогда, когда мы совсем их не ожидаем.',
    'Чем больше света мы дарим другим, тем светлее становится наш собственный путь.',
    'У каждого человека есть своя весна, которая однажды обязательно придёт.',
    'Терпение позволяет увидеть, как мечты постепенно становятся реальностью.',
    'Не всё, что приходит медленно, приходит слишком поздно.',
    'Счастье редко живёт в будущем или прошлом — чаще всего оно находится прямо сейчас.',
    'Самые красивые истории начинаются с простого желания не сдаваться.',
    'Иногда нужно потеряться, чтобы найти дорогу к самому себе.',
    'Ни одна ночь не длится вечно, как и ни одна буря.',
    'Любовь измеряется не словами, а тем, сколько тепла остаётся после них.',
    'Мы становимся богаче не благодаря тому, что получаем, а благодаря тому, чем делимся.',
    'Каждый новый день — это чистая страница, на которой ещё можно написать что-то прекрасное.',
  ],
} as const;
